### ISSUE TITLE
Adding annotations to generated entities

### ISSUE THREAD

**Issue by foot** [AntoineDao/backstage-provider-kubernetes#4]
Hiya!

For our use case we'd like to reflect annotations from kubernetes onto the reflected backstage entities.

https://github.com/backstage/backstage/issues/18617 outlines some possible labels:

```
annotations:
    backstage.io/kubernetes-lifecycle: production
    backstage.io/kubernetes-owner: team:eu-cluster-admins
    backstage.io/kubernetes-description: This is the production cluster
    backstage.io/kubernetes-system: test-system
    backstage.io/kubernetes-tags: 'eu,production,aws' # these are split on commas and trimmed
```

WDYT? Are you open to PRs on this project?
